services:
  base:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./models:/app/models
      - ./input:/app/input
      - ./output:/app/output
    environment:
      - PYTHONPATH=/app
    working_dir: /app

  train:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./models:/app/models
    environment:
      - PYTHONPATH=/app
    working_dir: /app
    command: ["python", "train.py"]
    depends_on:
      - base

  eval:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - PYTHONPATH=/app
    working_dir: /app
    command: ["python", "eval.py"]
    depends_on:
      - train

  infer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./models:/app/models
      - ./input:/app/input
      - ./output:/app/output
    environment:
      - PYTHONPATH=/app
    working_dir: /app
    command: ["python", "infer.py"]
    depends_on:
      - eval

  tensorboard:
    image: tensorflow/tensorflow:latest
    volumes:
      - ./logs:/logs
    ports:
      - "6006:6006"
    command: tensorboard --logdir /logs --host 0.0.0.0